jobs:
  quality-check:
    env:
      NUGET_PACKAGES: ${{ github.workspace }}/.nuget/packages
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Project
        uses: actions/checkout@v3

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v4
        with:
          cache: true
          cache-dependency-path: '**/packages.lock.json'
          dotnet-version: ${{ matrix.dotnet-version }}

      - name: Install Dependencies
        run: |
          sudo apt-get update && sudo apt-get install -y redis-server

          dotnet restore --locked-mode

      - name: Run quality checks
        run: |
          # Check format.
          dotnet format --verify-no-changes

          # Run tests.
          dotnet test

          # Ensure pack works.
          dotnet pack --no-restore
    strategy:
      matrix:
        dotnet-version:
          - '9.0'

name: Quality Check

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]
